// Builds the two assets the pages load, each under a content-hashed filename so
// they can be cached immutably, repoints every page at the new names, and writes
// the matching Cache-Control rules into dist/_headers.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, unlinkSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { buildPages } from './lib/pages.mjs';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const tmp = join(root, '.cache', 'app.css');

mkdirSync(dirname(tmp), { recursive: true });

execFileSync(process.execPath, [
  join(root, 'node_modules', 'tailwindcss', 'lib', 'cli.js'),
  '-c', join(root, 'tailwind.config.js'),
  '-i', join(root, 'src', 'tailwind.css'),
  '-o', tmp,
  '--minify',
], { stdio: 'inherit', cwd: root });

const assets = [
  { src: tmp,                                dir: 'assets/css', base: 'app',        ext: 'css' },
  { src: join(root, 'src', 'calculator.js'), dir: 'assets/js',  base: 'calculator', ext: 'js'  },
];

const emitted = [];
for (const a of assets) {
  const body = readFileSync(a.src);
  const hash = createHash('sha256').update(body).digest('hex').slice(0, 10);
  const name = `${a.base}.${hash}.${a.ext}`;
  const outDir = join(dist, a.dir);
  mkdirSync(outDir, { recursive: true });
  // drop every earlier build of this asset, hashed or not
  const stale = new RegExp(`^${a.base}([.][0-9a-f]{10})?[.]${a.ext}$`);
  for (const f of readdirSync(outDir)) {
    if (stale.test(f) && f !== name) unlinkSync(join(outDir, f));
  }
  writeFileSync(join(outDir, name), body);
  emitted.push({ ...a, name, bytes: body.length,
    ref: new RegExp(`/${a.dir}/${a.base}(?:[.][0-9a-f]{10})?[.]${a.ext}`, 'g') });
}
rmSync(join(root, '.cache'), { recursive: true, force: true });

// pages first: they reference the hashed asset names
const cssAsset = emitted.find((a) => a.ext === 'css');
const jsAsset = emitted.find((a) => a.ext === 'js');
const built = buildPages(root, dist, `/${jsAsset.dir}/${jsAsset.name}`, `/${cssAsset.dir}/${cssAsset.name}`);

const pages = [];
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.html')) pages.push(p);
  }
})(dist);

const patched = new Map(emitted.map((a) => [a.name, 0]));
for (const p of pages) {
  const before = readFileSync(p, 'utf8');
  let after = before;
  for (const a of emitted) {
    const next = after.replace(a.ref, `/${a.dir}/${a.name}`);
    if (next !== after) patched.set(a.name, patched.get(a.name) + 1);
    after = next;
  }
  if (after !== before) writeFileSync(p, after);
}

// Name the exact files, never a wildcard. wrangler.json sets not_found_handling
// to single-page-application, so a path that does not exist answers 200 with the
// homepage -- a wildcard rule would pin that in caches for a year under a URL
// that is neither a stylesheet nor a script.
const BEGIN = '# --- generated by scripts/build.mjs: hashed assets ---';
const END = '# --- end generated ---';
const headersPath = join(dist, '_headers');
const headers = readFileSync(headersPath, 'utf8');
const nl = headers.indexOf('\r\n') !== -1 ? '\r\n' : '\n';
const lines = [BEGIN];
for (const a of emitted) {
  lines.push(`/${a.dir}/${a.name}`, '  Cache-Control: public, max-age=31536000, immutable', '');
}
lines.push(END);
const managed = lines.join(nl);
const start = headers.indexOf(BEGIN);
const updated = start === -1
  ? headers.trimEnd() + nl + nl + managed + nl
  : headers.slice(0, start) + managed + headers.slice(headers.indexOf(END) + END.length);
if (updated !== headers) writeFileSync(headersPath, updated);

console.log('');
console.log(`${built.length} pages rendered, ${built.reduce((n, p) => n + p.faq, 0)} FAQ entries inlined`);
for (const a of emitted) {
  console.log(`${a.name.padEnd(28)} ${(a.bytes / 1024).toFixed(1).padStart(6)} KB   ${patched.get(a.name)} page(s)`);
}
